sylius_backend_admin_user:
    resource: |
        alias: sylius.admin_user
        section: backend
        path: users
        except: ['show']
        redirect: index
        grid: sylius_backend_admin_user
        vars:
            all:
                subheader: sylius.ui.manage_users_able_to_access_administration_panel
                templates:
                    form: backend/admin_user/_form.html.twig
            index:
                icon: lock
        templates: backend/crud
    type: sylius.resource
