# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    _defaults:
        public: true

    app.behat.context.setup.admin_security:
        class: App\Behat\Context\Setup\AdminSecurityContext
        arguments:
            - "@app.behat.shared_storage"
            - "@app.behat.admin_security"
            - "@app.fixture.example_factory.admin_user"
            - "@sylius.repository.admin_user"

    app.behat.context.setup.admin_user:
        class: App\Behat\Context\Setup\AdminUserContext
        arguments:
            - "@app.behat.shared_storage"
            - "@app.fixture.example_factory.admin_user"
            - "@sylius.repository.admin_user"

    app.behat.context.setup.app_security:
        class: App\Behat\Context\Setup\AppSecurityContext
        arguments:
            - "@app.behat.shared_storage"
            - "@app.behat.app_security"
            - "@app.fixture.example_factory.app_user"
            - "@sylius.repository.app_user"

    app.behat.context.setup.customer:
        class: App\Behat\Context\Setup\CustomerContext
        arguments:
            - "@app.behat.shared_storage"
            - "@sylius.repository.customer"
            - "@sylius.manager.customer"
            - "@sylius.factory.customer"
            - "@sylius.factory.app_user"

    app.behat.context.setup.user:
        class: App\Behat\Context\Setup\UserContext
        arguments:
            - "@app.behat.shared_storage"
            - "@sylius.repository.app_user"
            - "@app.fixture.example_factory.app_user"
            - "@sylius.manager.app_user"
