# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.behat.context.ui.backend.managing_addresses:
        class: App\Behat\Context\Ui\Backend\ManagingAddressesContext
        arguments:
            - "@app.behat.page.backend.address.index"
            - "@app.behat.page.backend.address.create"
            - "@app.behat.page.backend.address.update"
            - "@app.behat.current_page_resolver"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.backend.managing_administrators:
        class: App\Behat\Context\Ui\Backend\ManagingAdministratorsContext
        arguments:
            - "@app.behat.page.backend.administrator.create"
            - "@app.behat.page.backend.administrator.index"
            - "@app.behat.page.backend.administrator.update"
            - "@app.behat.notification_checker"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.backend.managing_customers:
        class: App\Behat\Context\Ui\Backend\ManagingCustomersContext
        arguments:
            - "@app.behat.page.backend.customer.index"
            - "@app.behat.page.backend.customer.update"
            - "@app.behat.current_page_resolver"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.backend.notification:
        class: App\Behat\Context\Ui\Backend\NotificationContext
        arguments:
            - "@app.behat.notification_checker"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.frontend.address:
        class: App\Behat\Context\Ui\Frontend\AddressContext
        arguments:
            - "@app.behat.page.frontend.address.show"
            - "@app.behat.page.frontend.address.index"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.frontend.homepage:
        class: App\Behat\Context\Ui\Frontend\HomepageContext
        arguments:
            - "@app.behat.page.frontend.home"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.frontend.login:
        class: App\Behat\Context\Ui\Frontend\LoginContext
        arguments:
            - "@app.behat.page.frontend.home"
            - "@app.behat.page.frontend.account.login"
            - "@app.behat.page.frontend.account.register"
            - "@app.behat.page.frontend.account.request_password_reset"
            - "@app.behat.page.frontend.account.reset_password"
            - "@app.behat.notification_checker"
            - "@app.behat.current_page_resolver"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.email:
        class: App\Behat\Context\Ui\EmailContext
        arguments:
            - "@app.behat.shared_storage"
            - "@app.behat.email_checker"
        tags:
            - { name: fob.context_service }
