services:
    _defaults:
        autowire: true
        autoconfigure: true

    command_handlers:
        namespace: App\Command\
        resource: '../../src/Command/*'

    App\Command\Installer\InstallCommand:
        arguments:
            $cacheDir: '%kernel.cache_dir%'

    App\Command\Installer\InstallDatabaseCommand:
        arguments:
            $environment: '%kernel.environment%'

    App\Command\Installer\InstallAssetsCommand:
        arguments:
            $environment: '%kernel.environment%'

    App\Command\Installer\InstallSampleDataCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $environment: '%kernel.environment%'
