services:
    _defaults:
        autowire: true
        autoconfigure: true

    command_handlers:
        namespace: App\Command\
        resource: '../../recipes/monofony-core/src/Command/*'

    App\Command\Installer\InstallCommand:
        arguments:
            $cacheDir: '%kernel.cache_dir%'

    App\Command\Installer\InstallDatabaseCommand:
        arguments:
            $environment: '%kernel.environment%'

    App\Command\Installer\InstallAssetsCommand:
        arguments:
            $publicDir: '%kernel.project_dir%/public'
            $environment: '%kernel.environment%'

    App\Command\Installer\InstallSampleDataCommand:
        arguments:
            $publicDir: '%kernel.project_dir%/public'
            $environment: '%kernel.environment%'
