# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.context.customer:
        class: App\Context\CustomerContext
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"
        public: true
