services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Fixture\AdminUserFixture:
        arguments:
            $exampleFactory: '@App\Fixture\Factory\AdminUserExampleFactory'

    App\Fixture\AppUserFixture:
        arguments:
            $exampleFactory: '@App\Fixture\Factory\AppUserExampleFactory'

    App\Fixture\OAuthClientFixture:
        arguments:
            $exampleFactory: '@App\Fixture\Factory\OAuthClientExampleFactory'
