services:
    App\Fixture\Factory\AdminUserExampleFactory:
        arguments:
            - "@sylius.factory.admin_user"
        public: true

    App\Fixture\Factory\AppUserExampleFactory:
        arguments:
            - "@sylius.factory.app_user"
            - "@sylius.factory.customer"
        public: true

    app.fixture.example_factory.oauth_client:
        class: App\Fixture\Factory\OAuthClientExampleFactory
        arguments:
            - "@app.factory.oauth_client"
        public: true    