# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
     sylius.form.type.admin_user.validation_groups: ["sylius"]

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Form\Extension\:
        resource: '../../src/Form/Extension'

    App\Form\EventSubscriber\CustomerRegistrationFormSubscriber: ~

    App\Form\Type\User\AdminUserType:
        arguments:
            $dataClass: "%sylius.model.admin_user.class%"
            $validationGroups: [sylius]

    App\Form\Type\User\AppUserType:
        arguments:
            $dataClass: "%sylius.model.app_user.class%"
            $validationGroups: [sylius]

    App\Form\Type\User\AppUserRegistrationType:
        arguments:
            $dataClass: "%sylius.model.app_user.class%"
            $validationGroups: [sylius, sylius_user_registration]

    App\Form\Type\Customer\CustomerSimpleRegistrationType:
        arguments:
            $dataClass: "%sylius.model.customer.class%"
            $validationGroups: [sylius, sylius_user_registration]

    App\Form\Type\Customer\CustomerRegistrationType:
        arguments:
            $dataClass: "%sylius.model.customer.class%"
            $validationGroups: [sylius, sylius_user_registration, sylius_customer_profile]
