# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    App\Installer\Checker\CommandDirectoryChecker:
        public: true
        arguments:
            - "@filesystem"

    App\Installer\Provider\DatabaseSetupCommandsProvider:
        public: true
        arguments:
            - "@doctrine"

    App\Installer\Provider\DatabaseSetupCommandsProviderInterface: '@App\Installer\Provider\DatabaseSetupCommandsProvider'
