services:
    _defaults:
        autowire: true

    App\EventListener\CanonicalizerListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\EventListener\DefaultUsernameORMListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    App\EventListener\UserRegistrationListener:
        tags:
            - { name: kernel.event_listener, event: sylius.customer.post_register, method: handleUserVerification }
