services:
    _defaults:
        autowire: true

    App\Menu\AdminMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: app.admin.main } # The alias is what is used to retrieve the menu

    App\Menu\AccountMenuBuilder:
        tags:
            - { name: knp_menu.menu_builder, method: createMenu, alias: app.account } # The alias is what is used to retrieve the menu
