parameters:
    locale: fr_FR
    email_contact: contact@example.com
    email_name: Contact AppName
    email_sender: no-reply@example.com

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $environment: '%kernel.environment%'

    app_core_bundle:
        namespace: App\
        resource: '../../src/Monofony/MetaPack/CoreMeta/.recipe/src/*'
        exclude:
            - '../../src/Monofony/MetaPack/CoreMeta/.recipe/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
            - '../../src/Monofony/MetaPack/CoreMeta/.recipe/src/Controller/ResourceController.php'
            