services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    app_frontend:
        namespace: App\
        resource: '../../src/Monofony/Bundle/FrontBundle/Recipe/src/*'
        exclude: '../../src/Monofony/Bundle/FrontBundle/Recipe/src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
