services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $publicDir: '%kernel.project_dir%/public'
            $cacheDir: '%kernel.cache_dir%'
            $environment: '%kernel.environment%'

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: [doctrine.event_subscriber]

    app_core:
        namespace: App\
        resource: '../../src/monofony-core/src/*'
        exclude: '../../src/monofony-core/src/{DependencyInjection,Entity,Form/EventSubscriber/AddUserFormSubscriber.php,Migrations,Tests,Kernel.php}'

    # Data collectors
    App\Collector\AppCollector:
        tags:
            - { name: data_collector, template: 'data_collector/app.html.twig', id: app, priority: -513 }
