services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $publicDir: '%kernel.project_dir%/public'
            $cacheDir: '%kernel.cache_dir%'
            $environment: '%kernel.environment%'

    app_backend:
        namespace: App\
        resource: '../../recipes/monofony-backend/src/*'
        exclude: '../../recipes/monofony-backend/src/{DependencyInjection,Entity,Form/EventSubscriber/AddUserFormSubscriber.php,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    controller_backend:
        namespace: App\Controller\
        resource: '../../recipes/monofony-backend/src/Controller'
        tags: ['controller.service_arguments']
