services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $publicDir: '%kernel.project_dir%/public'
            $cacheDir: '%kernel.cache_dir%'
            $environment: '%kernel.environment%'

    app_core:
        namespace: App\
        resource: '../../recipes/monofony-core/src/*'
        exclude: '../../recipes/monofony-core/src/{DependencyInjection,Entity,Form/EventSubscriber/AddUserFormSubscriber.php,Migrations,Tests,Kernel.php}'

    # Data collectors
    App\Collector\AppCollector:
        tags:
            - { name: data_collector, template: 'data_collector/app.html.twig', id: app, priority: -513 }

    App\EventListener\DefaultUsernameORMListener:
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    App\EventListener\UserRegistrationListener:
        tags:
            - { name: kernel.event_listener, event: sylius.customer.post_register, method: handleUserVerification }
