parameters:
    locale: fr_FR
    email_contact: contact@app_name.com
    email_name: Contact AppName
    email_sender: no-reply@app_name.com

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $publicDir: '%kernel.project_dir%/public'
            $cacheDir: '%kernel.cache_dir%'
            $environment: '%kernel.environment%'

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags: [doctrine.event_subscriber]

    app_core_bundle:
        namespace: App\
        resource: '../../src/Monofony/Bundle/CoreBundle/Recipe/src/*'
        exclude: '../../src/Monofony/Bundle/CoreBundle/Recipe/src/{DependencyInjection,Entity,Form/EventSubscriber/AddUserFormSubscriber.php,Migrations,Tests,Kernel.php}'

    app_core:
        namespace: App\
        resource: '../../src/Core/recipe/src/*'
        exclude: '../../src/Core/recipe/src/{DependencyInjection,Entity,Form/EventSubscriber/AddUserFormSubscriber.php,Migrations,Tests,Kernel.php}'

    # Data collectors
    App\Collector\AppCollector:
        tags:
            - { name: data_collector, template: 'data_collector/app.html.twig', id: app, priority: -513 }

    App\Entity\OAuth\ClientManager:
        $class: '%fos_oauth_server.model.client.class%'
