services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    app_fixture:
        namespace: App\
        resource: '../../src/Monofony/Bundle/FixturesBundle/Recipe/src/*'
        exclude: '../../src/Monofony/Bundle/FixturesBundle/Recipe/src/{DependencyInjection,Entity,Form/EventSubscriber/AddUserFormSubscriber.php,Migrations,Tests,Kernel.php}'
