
.PHONY: calledFromVm app db resetdb testdb tests phpspec phpunit behat

calledFromVm:
	[ -e /home/vagrant ]

# ----------------- database rules -----------------

app:
	composer install --optimize-autoloader
	bin/console doctrine:migrations:migrate
	bin/console sy:fi:lo

db:
	@echo "Connecting to database"
	mysql -uroot -pvagrant $(PROJECT)_dev

resetdb: calledFromVm
	@echo "Resetting database"
	bin/console do:da:dr --force
	bin/console do:da:cr
	bin/console do:mi:mi
	bin/console sy:fi:lo

testdb: calledFromVm
	@echo "Preparing test database for phpunit tests (see tests.logs in case of error)"
	sed -i -e "s/dbname.*/dbname: test/" app/config/config_test.yml
	bin/console doctrine:migrations:migrate --env=test -n > tests.logs 2>&1
	bin/console cache:clear --no-warmup --env=test > tests.logs 2>&1

# ----------------- test rules -----------------

tests: phpspec phpunit behat
	@

phpspec: calledFromVm
	@echo "Running phpspec tests"
	bin/phpspec run --format=pretty --verbose --no-code-generation

phpunit: testdb
	@echo "Running phpunit tests"
	bin/phpunit

behat: testdb calledFromVm
	@echo "Running behat tests"
	bin/behat --tags ~javascript --tags ~todo

