# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        ui_customer_account:
            contexts:
                - App\Behat\Context\Hook\DoctrineORMContext

                - App\Behat\Context\Transform\CustomerContext
                - App\Behat\Context\Transform\SharedStorageContext

                - app.behat.context.setup.customer
                - app.behat.context.setup.app_security
                - app.behat.context.setup.user

                - App\Behat\Context\Ui\Frontend\AccountContext
            filters:
                tags: "@customer_account && @ui"
