# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        ui_customer_account:
            contexts:
                - App\Behat\Context\Hook\DoctrineORMContext

                - App\Behat\Context\Transform\CustomerContext
                - App\Behat\Context\Transform\SharedStorageContext

                - App\Behat\Context\Setup\CustomerContext
                - App\Behat\Context\Setup\AppSecurityContext
                - App\Behat\Context\Setup\UserContext

                - App\Behat\Context\Ui\Frontend\AccountContext
            filters:
                tags: "@customer_account && @ui"
