framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/backend/manifest.json'
        packages:
            backend:
                json_manifest_path: '%kernel.project_dir%/public/assets/backend/manifest.json'
            frontend:
                json_manifest_path: '%kernel.project_dir%/public/assets/frontend/manifest.json'
