parameters:
    # Adds a fallback if the env vars are not set. This allows you
        # to run cache:warmup even if your environment variables are not available
        # yet. You should not need to change this value.
        env(DATABASE_DRIVER): ''
        env(DATABASE_HOST): ''
        env(DATABASE_PORT): ''
        env(DATABASE_NAME): ''
        env(DATABASE_USER): ''
        env(DATABASE_PASSWORD): null

doctrine:
    dbal:
        driver:   '%env(resolve:DATABASE_DRIVER)%'
        host:     '%env(resolve:DATABASE_HOST)%'
        port:     '%env(resolve:DATABASE_PORT)%'
        dbname:   '%env(resolve:DATABASE_NAME)%'
        user:     '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
                