imports:
    - { resource: '../../src/Monofony/Pack/AdminPack/.recipe/config/packages/monofony_admin.yaml' }
    - { resource: '../../src/Monofony/Pack/AdminPack/.recipe/config/sylius/grids/**/*.yaml' }
