# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
imports:
    - { resource: "@FOSOAuthServerBundle/Resources/config/security.xml" }

parameters:
    app.security.admin_regex: "^/admin"
    app.security.api_regex: "^/api"
    app.security.app_regex: "^/(?!admin|api/.*|api$|media/.*)[^/]++"
    secret: '%env(resolve:APP_SECRET)%'

security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        sylius_admin_user_provider:
            id: sylius.admin_user_provider.email_or_name_based
        sylius_app_user_provider:
            id: sylius.app_user_provider.email_or_name_based
    encoders:
        Sylius\Component\User\Model\UserInterface: argon2i

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        admin:
            context: admin
            pattern: '%app.security.admin_regex%'
            provider: sylius_admin_user_provider
            form_login:
                provider: sylius_admin_user_provider
                login_path: sylius_backend_login
                check_path: sylius_backend_login_check
                failure_path: sylius_backend_login
                default_target_path: app_backend_dashboard
                use_forward: false
                use_referer: false
            remember_me:
                secret: "%secret%"
                path: /admin
                name: APP_ADMIN_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: sylius_backend_logout
                target: sylius_backend_login
            anonymous: true

        oauth_token:
            pattern: '%app.security.api_regex%/oauth/v2/token'
            security: false

        api:
            pattern: '%app.security.api_regex%/.*'
            provider: sylius_app_user_provider
            fos_oauth:  true
            stateless:  true
            anonymous: true

        app:
            switch_user: true
            context: app
            pattern: '%app.security.app_regex%'
            provider: sylius_app_user_provider
            form_login:
                provider: sylius_app_user_provider
                login_path: app_frontend_login
                check_path: app_frontend_login_check
                failure_path: app_frontend_login
                default_target_path: app_frontend_homepage
                use_forward: false
                use_referer: false
            remember_me:
                secret: "%env(APP_SECRET)%"
                name: APP_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: app_frontend_logout
                target: app_frontend_homepage
            anonymous: true

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: "%app.security.admin_regex%/_partial", role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: "%app.security.admin_regex%/_partial", role: ROLE_NO_ACCESS }
        - { path: "%app.security.app_regex%/_partial", role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: "%app.security.app_regex%/_partial", role: ROLE_NO_ACCESS }

        - { path: "%app.security.admin_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%app.security.api_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%app.security.app_regex%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: "%app.security.app_regex%/register", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%app.security.app_regex%/verify", role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: "%app.security.admin_regex%", role: ROLE_ADMIN }
        - { path: "%app.security.api_regex%/.*", role: ROLE_USER }
        - { path: "%app.security.app_regex%/account", role: ROLE_USER }
