imports:
    - { resource: '../../src/AdminPack/recipe/config/grids/backend/admin_user.yaml' }
    - { resource: '../../src/AdminPack/recipe/config/grids/backend/customer.yaml' }
    - { resource: "../../src/CorePack/recipe/config/packages/sylius_grid.yaml" }
