vich_uploader:
    db_driver: orm

    mappings:
        admin_avatar:
            uri_prefix: /media/avatar
            upload_destination: '%kernel.project_dir%/public/media/avatar'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
