source 'https://rubygems.org'

gem 'capistrano'
gem 'capistrano-symfony'
gem 'capistrano-composer'
gem 'capistrano-file-permissions', :git => 'https://github.com/capistrano/file-permissions', :ref => '0122fe4'
gem 'ed25519'
gem 'bcrypt_pbkdf'
gem 'ed25519'
gem 'bcrypt_pbkdf'
