include Makefile.install.dist
include Makefile.test.dist
include Makefile.validation.dist

docs-build-default:
	cd docs && sphinx-build -b html . build -a

install-default: composer-install app-install fixtures-load yarn-install yarn-build

start-default:
	symfony server:start --no-tls || bin/console server:start ${ARGS}

stop-default:
	symfony server:stop || bin/console server:stop

test-default: validate-all test-all

%:  %-default
	@  true
