TAGS?=~todo
CHROMEDRIVER_PATH?=/usr/local/bin/chromedriver
FORMAT?=progress
VERBOSITY?=-vvv

start-selenium:
	vendor/bin/selenium-server-standalone -Dwebdriver.chrome.driver=${CHROMEDRIVER_PATH}

test-all: test-phpspec test-phpstan test-psalm test-phpunit test-infection test-all-behat

test-behat:
	APP_ENV=test vendor/bin/behat --tags=${TAGS} ${ARGS} -f ${FORMAT} ${VERBOSITY}

test-all-behat: test-behat-without-javascript test-behat-with-javascript test-behat-with-cli

test-behat-without-javascript:
	APP_ENV=test vendor/bin/behat --tags=~javascript --tags=${TAGS} -f ${FORMAT} ${VERBOSITY}

test-behat-with-javascript:
	make start-selenium > /dev/null 2>&1 & sleep 5
	APP_ENV=test vendor/bin/behat --tags=javascript --tags=${TAGS} -f ${FORMAT} ${VERBOSITY}

test-behat-with-cli:
	APP_ENV=test vendor/bin/behat --tags=cli --tags=${TAGS} -f ${FORMAT} ${VERBOSITY}

test-infection:
	phpdbg -qrr vendor/bin/infection ${ARGS}

test-phpspec:
	phpdbg -qrr vendor/bin/phpspec run -n ${ARGS}

test-phpstan:
	APP_ENV=dev bin/console cache:clear
	APP_ENV=dev bin/console cache:warmup
	vendor/bin/phpstan analyse -c phpstan.neon -l 1 src

test-phpunit:
	APP_ENV=test vendor/bin/phpunit ${ARGS}

test-psalm:
	vendor/bin/psalm --show-info=false
