composer-install:
	composer install --no-interaction

app-install:
	bin/console app:install -n

fixtures-load:
	bin/console sylius:fixtures:load default --no-interaction

yarn-install:
	yarn install

yarn-build:
	yarn encore production
