app_frontend_homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'frontend/homepage/index.html.twig'

app_account:
    resource: "frontend/account.yml"
    prefix: "mon-compte"

app_frontend_address:
    resource: "frontend/address.yml"

sylius_security:
    resource: "frontend/security.yml"

app_frontend_partial:
    resource: "frontend/partial.yml"
    prefix: "/_partial"
