sylius_backend_customer:
    resource: |
        section: backend
        alias: sylius.customer
        templates: 'backend/crud'
        grid: sylius_backend_customer
        redirect: index
        vars:
            all:
                subheader: sylius.ui.manage_your_customers
                templates:
                    form: backend/customer/_form.html.twig
            index:
                icon: users
    type: sylius.resource

sylius_backend_customer_show:
    path: /customers/{id}
    defaults:
        _controller: sylius.controller.customer:showAction
        _sylius:
            section: backend
            template: backend/customer/show.html.twig
            permission: true
