# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #    service_name:
    #        class: App\Directory\ClassName
    #        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    App\Behat\Page\Frontend\Account\ChangePasswordPage:
        parent: app.behat.symfony_page
        public: false

    App\Behat\Page\Frontend\Account\DashboardPage:
        parent: app.behat.symfony_page
        public: false

    App\Behat\Page\Frontend\Account\LoginPage:
        parent: app.behat.symfony_page
        public: false

    App\Behat\Page\Frontend\Account\ProfileUpdatePage:
        parent: app.behat.symfony_page
        public: false

    App\Behat\Page\Frontend\Account\RegisterPage:
        parent: app.behat.symfony_page
        public: false

    App\Behat\Page\Frontend\Account\RequestPasswordResetPage:
        parent: app.behat.symfony_page
        public: false

    App\Behat\Page\Frontend\Account\ResetPasswordPage:
        parent: app.behat.symfony_page
        public: false

    App\Behat\Page\Frontend\Account\VerificationPage:
        parent: app.behat.symfony_page
        public: false
