# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

      app.behat.page.frontend.address.index:
          class: App\Behat\Page\Frontend\Address\IndexPage
          parent: app.behat.symfony_page
          public: false

      app.behat.page.frontend.address.show:
          class: App\Behat\Page\Frontend\Address\ShowPage
          parent: app.behat.symfony_page
          public: false
