imports:
    - { resource: contexts/cli.yaml }
    - { resource: contexts/hook.yaml }
    - { resource: contexts/setup.yaml }
    - { resource: contexts/transform.yaml }
    - { resource: contexts/ui.yaml }
