services:
    app.behat.element:
        class: FriendsOfBehat\PageObjectExtension\Element\Element
        abstract: true
        public: false
        arguments:
            $session: '@behat.mink.default_session'
            $minkParameters: '@behat.mink.parameters'

    App\Tests\Behat\Element\:
        resource: '../../tests/Behat/Element/*'
        parent: app.behat.element
        public: false
