default:
    formatters:
        pretty:
            verbose:  true
            paths:    false
            snippets: false

    extensions:
        Behat\MinkExtension:
            base_url: http://localhost:8080/
            default_session: symfony
            javascript_session: chrome
            sessions:
                symfony:
                    symfony: ~
                chrome:
                    selenium2:
                        browser: chrome
                        capabilities:
                            browserName: chrome
                            browser: chrome
                            version: ""
                            chrome:
                                switches:
                                    - "start-fullscreen"
                                    - "start-maximized"
                                    - "no-sandbox"

        FriendsOfBehat\SymfonyExtension:
            kernel:
                bootstrap: 'vendor/autoload.php'
                path: src/Kernel.php
                class: 'App\Kernel'
                debug: true

        FriendsOfBehat\ContextServiceExtension:
            imports:
                - "src/Behat/Resources/config/services.yml"

        FriendsOfBehat\CrossContainerExtension: ~

        FriendsOfBehat\VariadicExtension: ~

    gherkin:
        filters:
            tags: "~@todo"
