default:
    suites:
        ui_managing_addresses:
            contexts_services:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.setup.address
                - app.behat.context.setup.admin_security

                - app.behat.context.transform.address
                - app.behat.context.transform.shared_storage

                - app.behat.context.ui.backend.managing_addresses
                - app.behat.context.ui.backend.notification
            filters:
                tags: "@managing_addresses && @ui"