# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

default:
    suites:
        ui_viewing_addresses:
            contexts_services:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.transform.address
                - app.behat.context.transform.shared_storage

                - app.behat.context.setup.admin_security
                - app.behat.context.setup.address

                - app.behat.context.ui.frontend.address
            filters:
                tags: "@viewing_addresses && @ui"
