default:
    suites:
        ui_security:
            contexts:
                - AppBundle\Behat\Context\Hook\DoctrineORMContext
                - Behat\MinkExtension\Context\MinkContext
                - AppBundle\Behat\ApiContext
                - AppBundle\Behat\UtilsContext
                - AppBundle\Behat\CustomerContext
                - AppBundle\Behat\UserContext
            filters:
                tags: "@security && @ui"