default:
    suites:
        ui_security:
            contexts:
                - AppBundle\Behat\Context\Hook\DoctrineORMContext:
                    entityManager: '@doctrine.orm.entity_manager'
                - Behat\MinkExtension\Context\MinkContext
                - AppBundle\Behat\UtilsContext
                - AppBundle\Behat\CustomerContext
                - AppBundle\Behat\UserContext
            filters:
                tags: "@security && @ui"