sylius_backend_partial_customer_latest:
    path: /latest/{count}
    methods: [GET]
    defaults:
        _controller: sylius.controller.customer::indexAction
        _sylius:
            repository:
                method: findLatest
                arguments: ['!!int $count']
            template: $template
