parameters:
    locale: en_US

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $spoolDirectory: '%kernel.cache_dir%/spool'
            $minkParameters: '@behat.mink.parameters'

    app_tests_behat_core:
        namespace: App\Tests\Behat\
        resource: '../src/CorePack/recipe/tests/Behat/*'

    app_tests_behat_admin:
        namespace: App\Tests\Behat\
        resource: '../src/AdminPack/recipe/tests/Behat/*'

    app_tests_behat_front:
        namespace: App\Tests\Behat\
        resource: '../src/FrontPack/recipe/tests/Behat/*'

    App\Tests\Behat\Service\SecurityService:
        autowire: false

    app.behat.admin_security:
        class: App\Tests\Behat\Service\SecurityService
        arguments:
            $firewallContextName: "admin"

    app.behat.app_security:
        class: App\Tests\Behat\Service\SecurityService
        public: false
        arguments:
            $firewallContextName: "app"

    App\Tests\Behat\Context\Setup\AdminSecurityContext:
        arguments:
            $securityService: "@app.behat.admin_security"

    App\Tests\Behat\Context\Setup\AppSecurityContext:
        arguments:
            $securityService: "@app.behat.app_security"

    # Backend Pages
    App\Tests\Behat\Page\Backend\DashboardPage: null

    App\Tests\Behat\Page\Backend\Administrator\CreatePage:
        $routeName: 'sylius_backend_admin_user_create'
    App\Tests\Behat\Page\Backend\Administrator\IndexPage:
        $routeName: 'sylius_backend_admin_user_index'
    App\Tests\Behat\Page\Backend\Administrator\UpdatePage:
        $routeName: 'sylius_backend_admin_user_update'

    App\Tests\Behat\Page\Backend\Customer\IndexPage:
        $routeName: 'sylius_backend_customer_index'
    App\Tests\Behat\Page\Backend\Customer\UpdatePage:
        $routeName: 'sylius_backend_customer_update'
