imports:
    resource: "../src/Monofony/Bundle/CoreBundle/Resources/config/services_test.yaml"

parameters:
    locale: en_US

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $minkParameters: '@behat.mink.parameters'

    app_tests_behat_core:
        namespace: App\Tests\Behat\
        resource: '../src/Monofony/Bundle/CoreBundle/Recipe/tests/Behat/*'

    app_tests_behat_admin:
        namespace: App\Tests\Behat\
        resource: '../src/Monofony/Bundle/AdminBundle/Recipe/tests/Behat/*'

    app_tests_behat_front:
        namespace: App\Tests\Behat\
        resource: '../src/Monofony/Bundle/FrontBundle/Recipe/tests/Behat/*'
