app_frontend_homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'frontend/homepage/index.html.twig'

app_account:
    resource: "frontend/account.yaml"
    prefix: "mon-compte"

sylius_security:
    resource: "frontend/security.yaml"

app_frontend_partial:
    resource: "frontend/partial.yaml"
    prefix: "/_partial"
