services:
    _defaults:
        autoconfigure: true
        autowire: true

    # Data collectors
    Monofony\Bundle\CoreBundle\DataCollector\MonofonyDataCollector:
        tags:
            - { name: data_collector, template: '@MonofonyCore/DataCollector/monofony.html.twig', id: monofony, priority: -513 }
