services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $spoolDirectory: '%kernel.cache_dir%/spool'
            $minkParameters: '@behat.mink.parameters'

    Monofony\Bundle\CoreBundle\Tests\Behat\:
        resource: '../../Tests/Behat/*'
