default:
    formatters:
        pretty:
            verbose:  true
            paths:    false
            snippets: false

    extensions:
        Behat\MinkExtension:
            base_url: "http://localhost:8080/"
            default_session: symfony
            javascript_session: chrome
            sessions:
                symfony:
                    symfony2: ~
                chrome:
                    selenium2:
                        browser: chrome
                        capabilities:
                            browserName: chrome
                            browser: chrome
                            version: ""
                            chrome:
                                switches:
                                    - "start-fullscreen"
                                    - "start-maximized"
                                    - "no-sandbox"

        Behat\Symfony2Extension: ~

    gherkin:
        filters:
            tags: "~@todo"
