services:
    _defaults:
        public: true
        autowire: true

    App\Tests\Behat\Context\Transform\:
        resource: '../../../src/CorePack/recipe/tests/Behat/Context/Transform/*'
        autowire: true
        public: true
