services:
    _defaults:
        public: true
        autowire: true

    App\Tests\Behat\Context\Ui\:
        resource: '../../../tests/Behat/Context/Ui/*'
        autowire: true
        public: true
