services:
    _defaults:
        public: true
        autowire: true

    App\Tests\Behat\Context\Ui\:
        resource: '../../../src/monofony-core/tests/Behat/Context/Ui/*'
        autowire: true
        public: true

    App\Tests\Behat\Context\Ui\Backend\:
        resource: '../../../src/monofony-backend/tests/Behat/Context/Ui/Backend/*'
        autowire: true
        public: true

    App\Tests\Behat\Context\Ui\Frontend\:
        resource: '../../../src/monofony-frontend/tests/Behat/Context/Ui/Frontend/*'
        autowire: true
        public: true
