default:
    suites:
        ui_managing_customers:
            contexts:
                - App\Behat\Context\Hook\DoctrineORMContext

                - app.behat.context.setup.customer
                - app.behat.context.setup.admin_security

                - App\Behat\Context\Transform\CustomerContext
                - App\Behat\Context\Transform\SharedStorageContext

                - App\Behat\Context\Ui\Backend\ManagingCustomersContext
                - App\Behat\Context\Ui\Backend\NotificationContext
            filters:
                tags: "@managing_customers && @ui"