default:
    suites:
        ui_managing_customers:
            contexts:
                - app.behat.context.hook.doctrine_orm

                - app.behat.context.setup.customer
                - app.behat.context.setup.admin_security

                - App\Behat\Context\Transform\CustomerContext
                - App\Behat\Context\Transform\SharedStorageContext

                - app.behat.context.ui.backend.managing_customers
                - app.behat.context.ui.backend.notification
            filters:
                tags: "@managing_customers && @ui"