default:
    suites:
        ui_managing_customers:
            contexts:
                - App\Behat\Context\Hook\DoctrineORMContext

                - App\Behat\Context\Setup\CustomerContext
                - App\Behat\Context\Setup\AdminSecurityContext

                - App\Behat\Context\Transform\CustomerContext
                - App\Behat\Context\Transform\SharedStorageContext

                - App\Behat\Context\Ui\Backend\ManagingCustomersContext
                - App\Behat\Context\Ui\Backend\NotificationContext
            filters:
                tags: "@managing_customers && @ui"