#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Testing (Doctrine Migrations)" "Monofony"
run_command "make test-doctrine-migrations"
