#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Testing (Fixtures)" "Monofony"
retry_run_command "bin/console sylius:fixtures:load default --no-interaction"
