#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Testing (Installer)" "Monofony"
run_command "bin/console app:install --no-interaction -vvv"
