#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Testing (Phpspec)" "Monofony"
run_command "phpdbg -qrr vendor/bin/phpspec run --no-interaction -f dot"
