#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"


if [[ "${CI}" == "" ]]; then
    INFECTION_FILTER="";
else
    git remote set-branches --add origin $TRAVIS_BRANCH;
    git fetch;
    CHANGED_FILES=$(git diff origin/$TRAVIS_BRANCH --diff-filter=AM --name-only | grep src/ | paste -sd "," -);

    if [[ "${CHANGED_FILES}" == "" ]]; then
        CHANGED_FILES=nothing;
    fi

    INFECTION_FILTER="--filter=${CHANGED_FILES} --ignore-msi-with-no-mutations";

    echo "CHANGED_FILES=$CHANGED_FILES";
fi

INFECTION_FLAGS='--threads=4 --min-msi=30 --min-covered-msi=75'

print_header "Testing (Infection)" "Monofony"
run_command "phpdbg -qrr vendor/bin/infection $INFECTION_FLAGS $INFECTION_FILTER"
