#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

code=0

print_header "Testing prod requirements (Composer)" "Sylius"
run_command "APP_ENV=prod composer install --no-dev --no-interaction --prefer-dist" || code=$?
run_command "composer install --no-interaction --prefer-dist" || code=$?

exit ${code}
