#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

code=0

print_header "Validating (Twig templates)" "AppName"
run_command "bin/console lint:twig src/monofony-core/templates" || code=$?
run_command "bin/console lint:twig src/monofony-backend/templates" || code=$?
run_command "bin/console lint:twig src/monofony-frontend/templates" || code=$?

exit ${code}
