#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Validating (Doctrine schema)" "Monofony"
run_command "make validate-doctrine-schema"
