default:
    suites:
        ui_managing_administrators:
            contexts:
                - App\Behat\Context\Hook\DoctrineORMContext

                - app.behat.context.setup.admin_security
                - app.behat.context.setup.admin_user

                - App\Behat\Context\Transform\SharedStorageContext

                - app.behat.context.ui.backend.managing_administrators
                - app.behat.context.ui.backend.notification
            filters:
                tags: "@managing_administrators && @ui"