default:
    suites:
        ui_managing_administrators:
            contexts:
                - App\Behat\Context\Hook\DoctrineORMContext

                - app.behat.context.setup.admin_security
                - app.behat.context.setup.admin_user

                - App\Behat\Context\Transform\SharedStorageContext

                - App\Behat\Context\Ui\Backend\ManagingAdministratorsContext
                - App\Behat\Context\Ui\Backend\NotificationContext
            filters:
                tags: "@managing_administrators && @ui"