# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

      app.behat.page.backend.address.create:
          class: App\Behat\Page\Backend\Address\CreatePage
          parent: app.behat.page.backend.crud.create
          public: false
          arguments: ["app_backend_address_create"]

      app.behat.page.backend.address.index:
          class: App\Behat\Page\Backend\Address\IndexPage
          parent: app.behat.page.backend.crud.index
          public: false
          arguments: ["app_backend_address_index"]

      app.behat.page.backend.address.update:
          class: App\Behat\Page\Backend\Address\UpdatePage
          parent: app.behat.page.backend.crud.update
          public: false
          arguments: ["app_backend_address_update"]