#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../bash/common.lib.sh"

prepare_for_behat_with_js() {
    # Run Selenium with ChromeDriver
    run_command "bin/selenium-server-standalone -Dwebdriver.chrome.driver=$PWD/bin/chromedriver > /dev/null 2>&1 &"

    # Run webserver
    run_command "bin/console server:run 127.0.0.1:8080 --env=test --no-debug --quiet > /dev/null 2>&1 &"
}

run_behat() {
    local code=0

    print_header "Testing (Behat - brand new, javascript scenarios; @javascript && ~@todo && ~@cli)" "AppName"
    run_command "bin/behat --strict --no-interaction -vvv -f progress --tags=\"@javascript && ~@todo && ~@cli\"" || code=$?
    if [[ ${code} = 1 ]]; then
        run_command "bin/behat --strict --no-interaction -vvv -f progress --tags=\"@javascript && ~@todo && ~@cli\" --rerun" ; code=$?
    fi

    return ${code}
}

print_header "Preparing for testing (Behat - javascript scenarios; @javascript)" "AppName"
prepare_for_behat_with_js

run_behat
