# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define :app_name do |app_name_config|
        app_name_config.vm.box = "debian/jessie64"

        app_name_config.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 1024
            v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
        end

        app_name_config.vm.synced_folder "./../../", "/var/www/app_name", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc', 'nolock', 'actimeo=2']
        app_name_config.vm.network "private_network", ip: "10.0.0.200"

        # Shell provisioning
        app_name_config.vm.provision :shell, :path => "shell_provisioner/run.sh"
        app_name_config.vm.provision :shell, privileged: false, path: "shell_provisioner/module/app.sh"
    end
end