# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

        app.behat.context.setup.address:
            class: AppBundle\Behat\Context\Setup\AddressContext
            arguments:
                - "@app.behat.shared_storage"
                - "@__symfony__.app.fixture.example_factory.address"
                - "@__symfony__.app.repository.address"
            tags:
                - { name: fob.context_service }

        app.behat.context.setup.admin_security:
            class: AppBundle\Behat\Context\Setup\AdminSecurityContext
            arguments:
                - "@app.behat.shared_storage"
                - "@app.behat.admin_security"
                - "@__symfony__.app.fixture.example_factory.admin_user"
                - "@__symfony__.sylius.repository.admin_user"
            tags:
                - { name: fob.context_service }

        app.behat.context.setup.customer:
            class: AppBundle\Behat\Context\Setup\CustomerContext
            arguments:
                - "@app.behat.shared_storage"
                - "@__symfony__.app.fixture.example_factory.app_user"
                - "@__symfony__.sylius.repository.customer"
            tags:
                - { name: fob.context_service }
