app_frontend_address_show:
    methods: [GET]
    path: /addresses/{id}
    defaults:
        _controller: app.controller.address:showAction
        _sylius:
            template: frontend/address/show.html.twig
            section: frontend

app_frontend_address_index:
    methods: [GET]
    path: /addresses/
    defaults:
        _controller: app.controller.address:indexAction
        _sylius:
            template: frontend/address/index.html.twig
            section: frontend
            grid: app_frontend_address
            paginate: 9
