sylius_grid:
    grids:
        app_backend_address:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.model.address.class%"
            sorting:
                city: asc
            fields:
                street:
                    type: string
                    label: sylius.ui.street
                    sortable: ~
                postcode:
                    type: string
                    label: sylius.ui.postcode
                    sortable: ~
                city:
                    type: string
                    label: sylius.ui.city
                    sortable: ~
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [street, postcode, city]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
