sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                admin_user:
                    name: "admin_user"
                    options:
                        custom:
                            -
                                email: "admin@example.com"
                                password: "admin"
                                enabled: true
                                first_name: "John"
                                last_name: "Doe"

                app_user:
                   options:
                       custom:
                           -
                               email: "customer@example.com"
                               password: "password"
                               first_name: "Harry"
                               last_name: "Cover"
                               enabled: true
                       random: 10

                api_client:
                    options:
                        custom:
                            client:
                                random_id: '%env(OAUTH_CLIENT_ID)%'
                                secret: '%env(OAUTH_SECRET)%'
                                allowed_grant_types: [password, access_token, refresh_token]
