sylius_grid:
    grids:
        sylius_backend_admin_user:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\User\AdminUser
            sorting:
                email: desc
            fields:
                firstName:
                    type: string
                    label: sylius.ui.first_name
                    sortable: ~
                lastName:
                    type: string
                    label: sylius.ui.last_name
                    sortable: ~
                username:
                    type: string
                    label: sylius.ui.username
                    sortable: ~
                email:
                    type: string
                    label: sylius.ui.email
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [email, username, firstName, lastName]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
