name: Split Monorepo (Monoplus POC)

on:
    push:
        branches:
            - 0.10
        paths:
            - 'src/**'
    workflow_dispatch: ~

jobs:
    split_monorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        steps:
            -   uses: actions/checkout@v3
                with:
                    fetch-depth: 0

            -   name: Monorepo Split of BehatBridge
                uses: alphpaca/monoplus-split-action@2022.1-alpha6
                with:
                    package_path: 'src/Monofony/Bridge/Behat'
                    personal_access_token: ${{ secrets.ACCESS_TOKEN }}
                    git_username: 'loic425'
                    git_email: 'lc.fremont@gmail.com'
                    repository_owner: "Monofony"
                    repository_name: "BehatBridge"
