imports:
    - { resource: '../sylius/resources.yaml' }
    - { resource: "@SyliusCustomerBundle/Resources/config/app/config.yml" }
    - { resource: "@SyliusUserBundle/Resources/config/app/config.yml" }

framework:
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'

liip_imagine:
    loaders:
        default:
            filesystem:
                locator: filesystem_insecure
                data_root:
                    - '%kernel.project_dir%/public'
    filter_sets:
        # @see http://symfony.com/doc/current/bundles/LiipImagineBundle/filters.html
        cache: ~
        default:
            quality: 100
            filters:
                auto_rotate: ~
                relative_resize: { scale: 1 }
        app_backend_admin_user_avatar_thumbnail:
            filters:
                thumbnail: { size: [50, 50], mode: outbound }

sylius_customer:
    resources:
        customer:
            classes:
                model: App\Entity\Customer\Customer
                repository: App\Repository\CustomerRepository

sylius_mailer:
    sender:
        name: '%email_name%'
        address: '%email_sender%'
    emails:
        contact_request:
            subject: app.emails.contact_request.subject
            template: emails/contactRequest.html.twig
        user_registration:
            subject: app.emails.user_registration.subject
            template: emails/userRegistration.html.twig
        reset_password_token:
            subject: app.emails.user.password_reset.subject
            template: emails/passwordReset.html.twig
        verification_token:
            subject: app.emails.user.verification_token.subject
            template: emails/verification.html.twig

security:
    password_hashers:
        argon2i: argon2id

sylius_user:
    resources:
        app:
            user:
                classes:
                    model: App\Entity\User\AppUser
                    repository: App\Repository\UserRepository
                    form: App\Form\Type\User\AppUserType
        admin:
            user:
                classes:
                    model: App\Entity\User\AdminUser
                    repository: Sylius\Bundle\UserBundle\Doctrine\ORM\UserRepository
                    form: App\Form\Type\User\AdminUserType
        admin_oauth:
            user:
                classes:
                    model: Sylius\Component\User\Model\UserOAuth
                    interface: Sylius\Component\User\Model\UserOAuthInterface
                    controller: Sylius\Bundle\ResourceBundle\Controller\ResourceController

vich_uploader:
    mappings:
        admin_avatar:
            uri_prefix: /media/avatar
            upload_destination: '%kernel.project_dir%/public/media/avatar'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
